name: Pre Merge Checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run all the tests
        run: ./gradlew test

  lint:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run lint
        run: ./gradlew lint
